# Generated by Django 2.2 on 2021-01-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencydetail',
            name='travmaks_partner',
            field=models.BooleanField(default=False),
        ),
    ]
