# Generated by Django 2.2 on 2021-01-17 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_agencydetail_travmaks_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideServiceArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GuideService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('service_area', models.ManyToManyField(to='accounts.GuideServiceArea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guideservice', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
