# Generated by Django 2.2 on 2021-02-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_agencyrequestcallback'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencydetail',
            name='agencyEmail',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
