# Generated by Django 2.2 on 2021-02-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_agencydetail_agencyemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencydetail',
            name='agency_logo',
            field=models.ImageField(blank=True, null=True, upload_to='agency_logo'),
        ),
    ]
