# Generated by Django 2.2 on 2021-02-24 16:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travelagency', '0003_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='creationDate',
        ),
        migrations.AddField(
            model_name='tour',
            name='creationDateTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
