# Generated by Django 2.2 on 2021-02-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelagency', '0004_auto_20210224_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
