# Generated by Django 2.2 on 2021-01-02 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traveller', '0002_auto_20201231_1627'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TourWishList',
        ),
    ]
